### ISSUE TITLE
not available as Pod

### ISSUE THREAD

**Issue by marinofelipe** [raphaelmansuy/cuid#4]
**Describe the bug**
Cuid is not available as a Pod.

**To Reproduce**
1. add 'cuid' to project Podfile
2. run 'pod install'
4. Error: `CocoaPods could not find compatible versions for pod "cuid"`

**Expected behavior**
Cuid should be correctly exposed as a Pod

**Smartphone (please complete the following information):**
- Cocoapods version: `1.5.0`

**Comment by raphaelmansuy** [comment]
Dear felipe,

i have tested with this Podfile

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCuid2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCuid2
  #
  
  pod "cuid"

  target 'TestCuid2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestCuid2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

And it's working.

**Comment by marinofelipe** [comment]
Ah, I got the problem. My Podfile had `platform :ios, '9.0'` uncommented. It seems `cuid` it's only available in higher iOS versions.
